# Generated by Django 5.2.5 on 2025-08-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeUsuario', models.CharField()),
                ('emailUsuario', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('idTarefa', models.CharField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Media'), ('A', 'Alta')])),
                ('dataCadastro', models.DateField()),
                ('status', models.CharField(choices=[('Fazer', 'Fazer'), ('Fazendo', 'fazendo'), ('pronto', 'pronto')])),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
    ]
