# Generated by Django 5.2.5 on 2025-08-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_tarefa_idtarefa_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(),
        ),
    ]
